apiVersion: v1
kind: Service
metadata:
  name: frontend-pwa-client
  labels:
    run: frontend-pwa-client
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: frontend-pwa-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-pwa-client
spec:
  replicas: 1
  selector:
    matchLabels:
      run: frontend-pwa-client
  template:
    metadata:
      labels:
        run: frontend-pwa-client
    spec:
      containers:
      - name: frontend-pwa-client
        image: DOCKERHUB/pwa-client:1.1.65
        resources:
          requests:
            cpu: "10m"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
